spring.application.name=demo

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Schemat z pliku SQL przy starcie (bez Hibernate/JPA)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

jwt.secret=x0stAAToufS61P0ykE6GjzjsCwNNFNd9TLOs3fQcRB14C1ZHVKlnRD9wp4756P1nuTJLGPZ8x9ijC4iTRurWQg
jwt.expiration=86400000
